#!/bin/bash
#
# vmcontext_hepix 
#
# chkconfig: 345 50 50
# description: HEPiX compliant contextualisation
#
### BEGIN INIT INFO
# Provides: $vmcontext_hepix
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: HEPiX contextualization
# Description: HEPiX contextualization 
### END INIT INFO

# Source function library

AMICONFIG="/usr/sbin/amiconfig.sh"

. /etc/init.d/hepix_functions

start() {
    echo "Starting vmcontext_hepix ..."
    setupContext
    # now run amiconfig with default ustings to proceess user data
    $AMICONFIG user
    # now run amiconfig with site/hepix plugin enabled only to enforce site policies
    $AMICONFIG hepix
    RETVAL=$?
    return $RETVAL
}

stop() {
    return 0
}

case "$1" in
    start)
                start
                RETVAL=$?
                ;;
    stop)
                stop
                RETVAL=$?
                ;;
        *)
        echo $"Usage: $0 {start|stop}"
        RETVAL=2
esac

exit $RETVAL
