#!/bin/sh

ConfigFile () {
  file=$1
  shift 1
  line=$*
  key=`echo $line | cut -d= -f1,1`
  val=`echo $line | cut -d= -f2-`
  cp -f $file $file.orig
  if [ `grep -c "^$key.*$separator" $file.orig` -gt 0 -a $append -eq 0 ]
  then
     sed "s#^$key.*$separator.*#$key$separator$val#" $file.orig    
  else
     cat $file.orig
     echo $key$separator$val
  fi > $file
}

ConfigTemplate () {
  template=$1
  shift 1
  file=$1
  shift 1
  line=$*
  key=`echo $line | cut -d= -f1,1`
  val=`echo $line | cut -d= -f2-`
  sed "s#@$key@#$val#" $template > $file
}

separator=" "
append=0

for var in $*
do
  case $1 in
      -a|--append)
           shift 1
           append=1
           ;;
      -f|--file)
           shift 1
           file=$1
           shift 1
           ;;
      -t|--template)
           shift 1
           template=$1
           shift 1
           ;;
      -s|--separator)
           shift 1
           separator=$1
           shift 1
           ;;
          *)
           break
           ;;
   esac
done

if [ ! -z $file ]
then
  if [ ! -z $template ]
  then
      ConfigTemplate $template $file $*
  else
    if [ -f $file ]
    then
      ConfigFile $file $*
    else
      exit 1
    fi
  fi 
else
  exit 1
fi
