#!/bin/bash
#
# vmcontext_prolog  Bring up/down contextualization
#
# chkconfig: 345 2 85
# description: HEPiX compliant contextualisation prolog
#
### BEGIN INIT INFO
# Provides: $vmcontext_prolog
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6 
# Short-Description: HEPiX contextualization prolog
# Description:  HEPiX contextualization early startup activities
### END INIT INFO

# Source function library
. /etc/init.d/functions
. /etc/init.d/hepix_functions


start() {
    echo "Starting vmcontext_prolog... "
    rm -rf $CONTEXT_DIR
    mkdir -p $CONTEXT_DIR
    getResourcesFromCD
    (
        loadContext
        setupContext
        runContextualizationScript "prolog" "start"
    )
    RETVAL=$?
    finalize "prolog" "start"
    echo
    return $RETVAL
}

stop() {
    (
        loadContext
        runContextualizationScript "prolog" "stop"
    )
    RETVAL=$?
    finalize "prolog" "stop"
    rm -rf $CONTEXT_DIR
    return $RETVAL
}

case "$1" in
    start)
                start
                RETVAL=$?
                ;;
    stop)
                stop
                RETVAL=$?
                ;;
        *)
        echo $"Usage: $0 {start|stop}"
        RETVAL=2
esac

exit $RETVAL
